# Site Settings
name: "Khaled Hikmat"
title: "Khaled Hikmat"
tagline: "Coding Thoughts"
sidebar_image: /images/cover.jpg

# Build Settings
markdown: kramdown
kramdown: 
  input: GFM
permalink: /:year-:month-:day/:title
baseurl: 
encoding: utf-8
highlighter: rouge
